#! /bin/sh

go get -u github.com/golang/protobuf/protoc-gen-go
go get -u github.com/gogo/protobuf/protoc-gen-gogo
go get -u github.com/golang/dep/cmd/dep
go get -u github.com/mdempsky/gocode
go get -u github.com/rogpeppe/godef
go get -u github.com/josharian/impl
go get -u golang.org/x/tools/cmd/...
go get -u honnef.co/go/tools/...
go get -u github.com/davidrjenni/reftools/cmd/fillstruct
go get -u github.com/sourcegraph/go-langserver
# metalinter
cd ~/
curl -L https://git.io/vp6lP | sh
go get -u github.com/golangci/golangci-lint
cd $GOPATH/src/github.com/golangci/golangci-lint/cmd/golangci-lint
go install -ldflags "-X 'main.version=$(git rev-parse --abbrev-ref HEAD)' -X 'main.commit=$(git rev-parse --short HEAD)' -X 'main.date=$(date)'"
