#! /bin/sh

go get -u github.com/golang/dep/cmd/dep
go get -u github.com/nsf/gocode
#go get -u github.com/rogpeppe/godef
echo "github.com/rogpeppe/godef is forked (check https://github.com/rogpeppe/godef/pull/77)"
go get -u github.com/josharian/impl
go get -u golang.org/x/tools/cmd/...
go get -u gopkg.in/alecthomas/gometalinter.v2
go get -u honnef.co/go/tools/...
go get -u github.com/davidrjenni/reftools/cmd/fillstruct
go get -u github.com/sourcegraph/go-langserver
gometalinter.v2 --install
